name: Build and Publish to GCR

on:
  push:
    branches:
    - master

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  IMAGE: api-gateway

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

    - run: |
        gcloud auth configure-docker

    - name: Build
      run: |
        docker build --target prod -t asia.gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA .
    
    - name: Publish
      run: |
        docker push asia.gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
# on: [push]

# jobs:
#   test:
#     name: test
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master

#     - name: run test
#       uses: cedrickring/golang-action/go1.13@1.4.1
#       env:
#         GO111MODULE: "on"
#         PROJECT_PATH: "./src"
#       with:
#         args: |
#           go test -coverprofile=cover.out ./...
#           ls

#     - uses: codecov/codecov-action@v1
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         file: ./cover.out